FROM nginx:alpine

# Copy custom nginx config
COPY nginx.conf /etc/nginx/nginx.conf

# Copy static files
COPY html /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Nginx stays in foreground
CMD ["nginx", "-g", "daemon off;"]
